//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。C:\Users\Administrator\Desktop\QP.Prospectus\QP.Prospectus\App_Data\
// </auto-generated>
//------------------------------------------------------------------------------

namespace QP.Prospectus.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.Web;

    public partial class businessplan
    {
        [ReadOnly(true)]
        public string Id { get; set; }
        [Required(ErrorMessage = "请填写信息")]
        [Display(Name = "您希望联系哪位合伙人")]
        public string Partner { get; set; }

        [Required(ErrorMessage = "请填写信息")]
        [Display(Name = "项目/产品叫什么（限10字)")]
        public string ProjectName { get; set; }

        [Required(ErrorMessage = "请填写信息")]
        [Display(Name = "用一句话说明白你的项目/产品 (限70字）")]
        public string ProjectDescribe { get; set; }

        [Required(ErrorMessage = "请填写信息")]
        [Display(Name = "你试图解决什么样的的痛点/问题（限70字）")]
        public string C__Setback { get; set; }


        [Required(ErrorMessage = "请填写信息")]
        [Display(Name = "为什么你的团队能胜任这个工作（限70字）")]
        public string TeamDescribe { get; set; }

        [Required(ErrorMessage = "请填写信息")]
        [Display(Name = "一句最能打动你的名言（限20字)")]
        public string Dictum { get; set; }


        [Required(ErrorMessage = "请填写信息")]
        [Display(Name = "为了这个项目你愿意投入什么？")]
        public string C__ProjectPayOut { get; set; }

        [Required(ErrorMessage = "请填写信息")]
        [Display(Name = "融多少钱 ? 出让多少股份 ?（限20字)")]
        [RegularExpression(@"^[0-9]*$" ,ErrorMessage = "只能输入数字")]
        public Nullable<decimal> PayMoney { get; set; }

        [Required(ErrorMessage = "请选择信息")]
        [Display(Name = "符合您项目的关键词(多选)")]
        public string ProjectTantistop { get; set; }


        [Display(Name = "请上传您的BP")]
        [Required(ErrorMessage = "请上传您的BP")]
        public string FilePath { get; set; }

        [Required(ErrorMessage = "请选择信息")]
        [Display(Name = "姓名")]

        public string Name { get; set; }

        [Required(ErrorMessage = "请选择信息")]
        [Display(Name = "性别")]
        public string Sex { get; set; }

        [Required(ErrorMessage = "请填写信息")]
        [Display(Name = "Email")]
        [EmailAddress(ErrorMessage = "邮箱格式不正确")]
        public string Email { get; set; }

        [Required(ErrorMessage = "请填写信息")]
        [Display(Name = "手机号")]
        [RegularExpression(@"^1[3458][0-9]{9}$" , ErrorMessage = "手机号格式不正确")]
        public string Phone { get; set; }

        [Required(ErrorMessage = "请填写信息")]
        [Display(Name = "微信号")]
        public string WeChat { get; set; }

        [Required(ErrorMessage = "请填写信息")]
        [Display(Name = "生日")]
        [DataType(DataType.Date)]
        public Nullable<System.DateTime> Birthday { get; set; }


        [Display(Name = "公司注册名称（如果有的话）")]
        [StringLength(20, ErrorMessage = "公司注册名称请控制在100字之内")]
        public string C__CompanyName { get; set; }

        [Display(Name = "网址（如果有的话）")]
        public string CompanyUrl { get; set; }

        [Display(Name = "地址")]
        public string Address { get; set; }

        [StringLength(100,ErrorMessage ="详细地址请控制在100字之内")]
        public string InDetails { get; set; }
    }
}
