//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace QP.Prospectus.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class confige
    {
        public int id { get; set; }        
        public string webName { get; set; }
        public string brief { get; set; }
        public string Parthers { get; set; }
        public string keyWord { get; set; }
        public string PayOut { get; set; }
    }
}
